"""add asset slug

Revision ID: d6ca49a096aa
Revises: 06335a8bd0f1
Create Date: 2026-08-30 13:49:22.137157+00:00
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd6ca49a096aa'
down_revision: Union[str, None] = '06335a8bd0f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('slug', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_assets_slug'), 'assets', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_slug'), table_name='assets')
    op.drop_column('assets', 'slug')
    # ### end Alembic commands ###